--- # Installing Cassandra on Single Server (Stage Installation - Final Playbook). You need to specify two variable: 'target' and 'enviro'. enviro = variable is for keyspaces. You need to specify which environment it is. 
- hosts: '{{ target }}'
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Add Java Repo 
    shell: "add-apt-repository ppa:webupd8team/java -y"

  - name: Update all packages to the latest version
    shell: "apt-get -y update"

# Accept oracle license

  - name: Accepting Oracle license 1
    shell: "echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections"

  - name: Accepting Oracle License 2
    shell: "echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections"

  - name: Install Java8
    shell: "apt-get -y install oracle-java8-set-default"

# Install Cassandra

  - name: Add Cassandra Repository 
    shell: "echo 'deb http://debian.datastax.com/community stable main' | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list"

  - name: Add Secondary Cassandra Repository 
    shell: "echo 'deb-src http://www.apache.org/dist/cassandra/debian 22x main' | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list"

  - name: Add Keys
    shell: "wget http://debian.datastax.com/debian/repo_key"
  - name: Adding Keys
    shell: "apt-key add repo_key"

  - name: Add Additional Keys That Are Needed
    shell: "curl https://www.apache.org/dist/cassandra/KEYS | apt-key add -"

  - name: Update Packages One More Time
    shell: "apt-get -y update"
  - name: Install Cassandra
    shell: "apt-get -y install dsc22=2.2.3-1 cassandra=2.2.3"

# This sleep is must in this playbook, otherwise, your cassandra installation will fail.

  - name: Wait two minutes and let the Ansible relax!
    shell: "sleep 150"

# Configuring Ansible files

  - name: Editing listen_address value inside cassandra config
    shell: "sed -i '429s/localhost/''{{target}}''/' /etc/cassandra/cassandra.yaml"
  
  - name: Editing /etc/init.d/cassandra
    shell: "sed -i 's/cassandra.+CassandraDaemon/cassandra/' /etc/init.d/cassandra"
  
  - name: Setting rpc_address value to 0.0.0.0
    shell: "sed -i '487s/localhost/0.0.0.0/' /etc/cassandra/cassandra.yaml"    
  
  - name: Uncommenting broadcast_rpc_address
    shell: "sed -i '498s/^#//' /etc/cassandra/cassandra.yaml"
  
  - name: Adding IP address to broadcast_rpc_address
    shell: "sed -i '498s/1.2.3.4/''{{target}}''/' /etc/cassandra/cassandra.yaml"
  
  - name: Remove whitespace in front of broadcast_rpc_address
    shell: "sed -i '498s/^ *//' /etc/cassandra/cassandra.yaml"

# File needs to be placed under /home/ as /home/downstream.cql and /home/segment.cql inside target server
# Make sure to inlcude MCLOL string and attach it to 'sg' inside segment.cql

  - name: Wait 7 seconds and let Ansible rest!
    shell: "sleep 7"

  - name: Copying downstream.cql file to target server
    copy: src=/application_deploy/files/downstream.cql dest=/home/
  - name: Copying over segment.cql file
    copy: src=/application_deploy/files/segment.cql dest=/home/

  - name: Edit downstream CQL file
    shell: "sed -i 's/MCLOL/''{{enviro}}''/' /home/downstream.cql"

  - name: Run the downstream file with CQL commands
    shell: "cqlsh -f /home/downstream.cql"

  - name: Edit segment CQL file
    shell: "sed -i 's/MCLOL/''{{enviro}}''/' /home/segment.cql"

  - name: Run segment CQL file
    shell: "cqlsh -f /home/segment.cql"

  - name: Restart Cassandra
    shell: "service cassandra restart"
